# Generated by Django 5.2.13 on 2026-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chatmessage_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('expired', 'Hết hạn')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Chờ thanh toán'), ('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('active', 'Đang hiệu lực'), ('cancelled', 'Hủy đơn'), ('payment_expired', 'Hết hạn thanh toán')], default='awaiting_payment', max_length=20),
        ),
    ]
