# Generated by Django 5.2.13 on 2026-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_backfill_existing_order_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=80)),
                ('secondary_button_link', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(upload_to='banners/')),
                ('template', models.CharField(choices=[('single_left', '1 banner - chữ bên trái'), ('single_center', '1 banner - chữ giữa'), ('triple_grid', '3 banner - lưới chiến dịch'), ('custom_html', 'Custom HTML/CSS overlay')], default='single_left', max_length=30)),
                ('custom_html', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
