# Generated by Django 5.2.13 on 2026-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_existing_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='template',
            field=models.CharField(
                choices=[
                    ('single_left', '1 banner - chữ bên trái'),
                    ('single_center', '1 banner - chữ giữa'),
                    ('triple_grid', '3 banner - lưới chiến dịch'),
                    ('carousel', 'Slider nhiều banner'),
                    ('custom_html', 'Custom HTML/CSS overlay'),
                ],
                default='single_left',
                max_length=30,
            ),
        ),
    ]
