# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bannerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(
                choices=[('vi', 'Tiếng Việt'), ('en', 'English')],
                default='vi',
                max_length=5,
            ),
        ),
    ]
