# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_english_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=30, verbose_name='Mã ngân hàng VietQR')),
                ('account_no', models.CharField(max_length=50, verbose_name='Số tài khoản nhận tiền')),
                ('account_name', models.CharField(max_length=255, verbose_name='Tên chủ tài khoản')),
                ('template', models.CharField(default='compact2', max_length=30, verbose_name='Mẫu QR')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình thanh toán VietQR',
                'verbose_name_plural': 'Cấu hình thanh toán VietQR',
            },
        ),
    ]
