# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_paymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetting',
            name='payment_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Thời hạn QR (phút)'),
        ),
    ]
