# Generated by Codex on 2026-05-14

import uuid
from django.db import migrations, models


def populate_payment_tokens(apps, schema_editor):
    Order = apps.get_model('api', 'Order')
    for order in Order.objects.filter(payment_token__isnull=True):
        order.payment_token = uuid.uuid4()
        order.save(update_fields=['payment_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_paymentsetting_payment_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.RunPython(populate_payment_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
